version: '3'
services:

    script:
        build: .
        volumes:
<<<<<<< HEAD
            - ./:/home/script
        command: python3 scripts/script_popula_neo4j.py                
=======
            - ./:/home/script/
        command: python3 script_popula_neo4j.py                
>>>>>>> 8823b8d1105b5dd6d49f4a929c7d1d62de74b315
    neo4j:
        image: neo4j:latest
        ports:
            - '7474:7474'
            - '7687:7687'
        volumes:
            - $HOME/neo4j/data:/data

        environment:
            NEO4J_AUTH: none
            #NEO4J_dbms_connectors_default__listen__address: 0.0.0.0



